apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: foodist
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Efiop97/FoodistGitOps.git
    path: "apps/foodist"
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: foodist
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true  