elasticsearch:
  # Elasticsearch values
  global:
    elasticsearch:
      service:
        name: elasticsearch
        ports:
          restAPI: 9200
    kibanaEnabled: true

  master:
    masterOnly: false
    replicaCount: 1
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0

  sysctlImage:
    enabled: true

  kibana:
    ingress:
      enabled: true
      hostname: kibana.foodists.net
      path: /
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
      tls: true
      ingressClassName: "nginx"
    persistence:
      enabled: true
      size: 5Gi
    service:
      port:
        http: 5601

fluent-bit:
  enabled: true
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level {{ .Values.logLevel }}
          Parsers_File /fluent-bit/etc/parsers.conf
          Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On
    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*food*.log
          multiline.parser docker, cri
          Tag kube.*
          Mem_Buf_Limit 100MB
          Skip_Long_Lines On
      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On
    filters: |
      [FILTER]
          Name kubernetes
          Match kube.*
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
    outputs: |
      [OUTPUT]
          Name es
          Match kube.*
          Type  _doc
          Host efk-stack-elasticsearch
          Port 9200
          tls Off
          tls.verify Off
          Logstash_Format On
          Logstash_Prefix foodist
          Retry_Limit False
          Suppress_Type_Name On

      [OUTPUT]
          Name es
          Match host.*
          Type  _doc
          Host efk-stack-elasticsearch
          Port 9200
          tls Off
          tls.verify Off
          Logstash_Format On
          Logstash_Prefix node
          Retry_Limit False
          Suppress_Type_Name On