apiVersion: v1
kind: ConfigMap
metadata:
  name: foodist-conf
data:
  DB_HOST: {{ include "foodist.db.host" . }}
  DB_USER: {{ .Values.postgresql.auth.username }}
  DB_NAME: {{ .Values.postgresql.auth.database }}
  DB_PORT: {{ .Values.postgresql.service.ports.postgresql | quote }}
  PORT: {{ .Values.foodist.config.port | quote }}
  LOG_LEVEL: {{ .Values.foodist.config.logLevel | quote }}
  APP_ENV: "production"