{{- if .Values.foodist.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foodist-ingress
{{- if .Values.foodist.ingress.tls.enabled }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
{{- end }}
spec:
  ingressClassName: {{ .Values.foodist.ingress.ingressClassName | default "nginx" }}
{{- if .Values.foodist.ingress.tls.enabled }}
  tls:
    - hosts: 
        - {{ .Values.foodist.ingress.hostname }}
        - www.{{ .Values.foodist.ingress.hostname }}
      secretName: letsencrypt
{{- end }}
  rules:
    - host: {{ .Values.foodist.ingress.hostname }}
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: foodist-svc
                port:
                  number: {{ .Values.foodist.service.port | default "80" }}
            path: /
    - host: www.{{ .Values.foodist.ingress.hostname }}
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: foodist-svc
                port:
                  number: {{ .Values.foodist.service.port | default "80" }}
            path: /
    
{{- end }}