{{- if and .Values.foodist.ingress.enabled .Values.foodist.ingress.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
{{ if .Values.foodist.ingress.tls.staging }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
{{ else }}
    server: https://acme-v02.api.letsencrypt.org/directory
{{ end }}
    email: igor.mumladze@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
{{- end }}