apiVersion: v1
kind: Service
metadata:
  name: foodist-svc
  labels:
    app: foodist
spec:
{{ if .Values.foodist.ingress.enabled }}
  type: ClusterIP
{{ else }}
  type: {{ .Values.foodist.service.type | default "ClusterIP" }}
{{ end }}
  ports:
    - port: {{ .Values.foodist.service.port | default "80"}}
      targetPort: {{ .Values.foodist.config.port | default "5000"}}
  selector:
    app: foodist